### ISSUE TITLE
Application error on surveys 

### ISSUE THREAD

**Issue by johnhubertjj** [the-abe-train/plurality#11]
Hi!

This morning, when attempting to try the latest survey, an application error appeared instead (see attached). This appears to be across everything other than the landing page 

![Screenshot_20221111-104205_Samsung Internet](https://user-images.githubusercontent.com/21290448/201324169-f3dd763b-0982-43bb-aae6-1600c76128e0.jpg)

**Comment by the-abe-train** [comment]
I just fixed it. It was an error related to daylight savings time, I thought I fixed it for all the surveys on Sunday but looks like I missed one! Thanks for pointing it out.
